<?php

namespace Sentiment\facades;

use Illuminate\Support\Facades\Facade;

class Vaman extends Facade{

    protected static function getFacadeAccessor()
    {
        return 'Vaman';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}